version: '3.8'

services:
  pg:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: booking
    ports:
        - "5432:5432"
    volumes:
        - ./pgdata:/var/lib/postgresql/data