// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	entities "github.com/loxt/hotel-booking/booking/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// GuestService is an autogenerated mock type for the GuestService type
type GuestService struct {
	mock.Mock
}

// Save provides a mock function with given fields: guest
func (_m *GuestService) Save(guest *entities.Guest) error {
	ret := _m.Called(guest)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Guest) error); ok {
		r0 = rf(guest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewGuestService creates a new instance of GuestService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGuestService(t interface {
	mock.TestingT
	Cleanup(func())
}) *GuestService {
	mock := &GuestService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
